services:
  eticaret-app:
    build: .
    container_name: eticaret-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@localhost:1521:TEST
      - SPRING_DATASOURCE_USERNAME=	ADMIN
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always
